# Sample .travis.yml for R projects.
#
# See https://github.com/craigcitro/r-travis
#     https://github.com/eddelbuettel/r-travis/

language: c

# Opt into fully virtualized infrastructure
# cf http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/
sudo: required
bioc_required: true



before_install:
 - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
 - chmod 755 ./travis-tool.sh
 - ./travis-tool.sh bootstrap
  
install:
 - ./travis-tool.sh install_deps
 - ./travis-tool.sh install_bioc_deps
   - ./travis-tool.sh install_aptget r-cran-rcpp g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
  
script:
  - ./travis-tool.sh run_tests

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - PKG_CXXFLAGS="-std=c++11"