# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
sudo: required
bioc_required: true
warnings_are_errors: false

#before_install:
#  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
#  - chmod 755 ./travis-tool.sh
#  - ./travis-tool.sh bootstrap
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get update -qq

#install:
#  - ./travis-tool.sh install_deps
#  - ./travis-tool.sh install_bioc_deps
#  - sudo apt-get install -qq g++-4.8
#  - export CXX="g++-4.8"
  
#script: ./travis-tool.sh run_tests

#after_failure:
#  - ./travis-tool.sh dump_logs

#after_script:
#  - ./travis-tool.sh dump_logs_by_extension "timings"
#  - ./travis-tool.sh dump_sysinfo

addons:
  apt:
     sources:
     - ubuntu-toolchain-r-test
     packages:
     - gcc-4.8
     - g++-4.8
  
notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
    - CXX="g++-4.8"
    - CC="gcc-4.8"

